version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.1.4-20220427
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.1.4-20220427
    ports:
      - "7900:7900"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1

  firefox:
    image: selenium/node-firefox:4.1.4-20220427
    ports:
      - "7901:7900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1

# chrome_video:
#   image: selenium/video:ffmpeg-4.3.1-20220427
#    volumes:
#     - ./RecordedVideos:/videos
#   depends_on:
#     - chrome
#   environment:
#     - DISPLAY_CONTAINER_NAME=chrome
#     - FILE_NAME=chrome_video.mp4

